services:
  - type: web
    name: ethio-health-care
    env: python
    runtime: python-3.11
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATA_DIR
        value: /var/data
      - key: BASE_URL
        value: https://ethio-health-care.onrender.com
      - key: SMTP_USE_TLS
        value: "true"
      - key: SMTP_USE_SSL
        value: "false"
    disks:
      - name: ethio-health-care-data
        mountPath: /var/data
        sizeGB: 1
